import pygame

# SCALING AND FPS
FULL_SCREEN = 0
SCALE = 1
FPS = 60

# DISPLAY INFORMATION
NATIVE_WIDTH = 848
NATIVE_HEIGHT = 480
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)
NATIVE_WIDTH_CENTER = NATIVE_WIDTH // 2
NATIVE_HEIGHT_CENTER = NATIVE_HEIGHT // 2
NATIVE_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_HEIGHT_CENTER)
NATIVE_TOP = 0
NATIVE_RIGHT = NATIVE_WIDTH
NATIVE_BOTTOM = NATIVE_HEIGHT
NATIVE_LEFT = 0
NATIVE_TOP_LEFT = (NATIVE_LEFT, NATIVE_TOP)
NATIVE_TOP_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_TOP)
NATIVE_TOP_RIGHT = (NATIVE_WIDTH, NATIVE_TOP)
NATIVE_RIGHT_CENTER = (NATIVE_WIDTH, NATIVE_HEIGHT_CENTER)
NATIVE_BOTTOM_RIGHT = NATIVE_SIZE
NATIVE_BOTTOM_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_HEIGHT)
NATIVE_BOTTOM_LEFT = (NATIVE_LEFT, NATIVE_HEIGHT)
NATIVE_LEFT_CENTER = (NATIVE_LEFT, NATIVE_HEIGHT_CENTER)
DISPLAY_WIDTH = NATIVE_WIDTH * SCALE
DISPLAY_HEIGHT = NATIVE_HEIGHT * SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
DISPLAY_WIDTH_CENTER = DISPLAY_WIDTH // 2
DISPLAY_HEIGHT_CENTER = DISPLAY_HEIGHT // 2
DISPLAY_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_HEIGHT_CENTER)
DISPLAY_TOP = 0
DISPLAY_RIGHT = DISPLAY_WIDTH
DISPLAY_BOTTOM = DISPLAY_HEIGHT
DISPLAY_LEFT = 0
DISPLAY_TOP_LEFT = (DISPLAY_LEFT, DISPLAY_TOP)
DISPLAY_TOP_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_TOP)
DISPLAY_TOP_RIGHT = (DISPLAY_WIDTH, DISPLAY_TOP)
DISPLAY_RIGHT_CENTER = (DISPLAY_WIDTH, DISPLAY_HEIGHT_CENTER)
DISPLAY_BOTTOM_RIGHT = DISPLAY_SIZE
DISPLAY_BOTTOM_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_HEIGHT)
DISPLAY_BOTTOM_LEFT = (DISPLAY_LEFT, DISPLAY_HEIGHT)
DISPLAY_LEFT_CENTER = (DISPLAY_LEFT, DISPLAY_HEIGHT_CENTER)

# DIRECTORY INFORMATION
DIR_FONTS = "\\fonts\\"
DIR_IMAGES = "\\images\\"
DIR_MUSIC = "\\music\\"
DIR_SOUNDS = "\\sounds\\"
DIR_SPRITESHEETS = "\\spritesheets\\"

# ASSETS INFORMATION

# SPRITES/SPRITESHEETS
SHIP = pygame.image.load("src/spritesheets/Spaceship2.png")
LASER = pygame.image.load("src/images/Laser.png")
ASTEROID = pygame.image.load("src/images/Asteroid3.png")
DARK_ASTEROID = pygame.image.load("src/images/Dark_Asteroid.png")
DWELLER = pygame.image.load("src/spritesheets/Dweller2.png")
EXPLOSION = pygame.image.load("src/spritesheets/Explosion.png")

# HUD
HUD = pygame.image.load("src/images/Hud.png")

# ICON
ICON = pygame.image.load("src/images/Icon.png")

# FONT
FONT = "src/fonts/Grand9K_Pixel.ttf"

# SOUND EFFECTS
PROJECTILE_SOUND = "src/sounds/Laser.wav"
HIT_HURT_SOUND = "src/sounds/Hit_Hurt.wav"
EXPLOSION_SOUND = "src/sounds/Explosion.wav"
